# Generated by Django 6.0.6 on 2026-06-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novari_base', '0003_user_admintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(db_index=True, max_length=254)),
                ('Phone', models.CharField(db_index=True, max_length=20)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Address', models.TextField(default='')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Order_Notes', models.TextField(default='')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
